### ISSUE TITLE
[Bug]: Breaks extensions page

### ISSUE THREAD

**Issue by FenrirBots** [avoonix/vscode-language-pack-furry#1]
### Expected Behavior

To be able to view extension information.

### Actual Behavior

An error is thrown when viewing extension information.
![image](https://github.com/user-attachments/assets/d0400ef6-ad23-485a-86c3-5c043610cb0c)

### Steps to Reproduce the Problem

1. Install vscode-language-pack-furry
2. Go to the extensions tab
3. Click on any extension

**Comment by rsa17826** [comment]
i have the same issue, it is only when using the furry-owo and not just furry, it doesn't happen for locally installed extensions, only extensions that are not installed or are installed from the maketplace

```log
2025-11-10 18:09:12.057 [info] [Window] Started local extension host with pid 4320.
2025-11-10 18:09:12.519 [info] [Window] MCP Registry configured: https://api.mcp.github.com/2025-09-15
2025-11-10 18:09:12.683 [info] [Window] Settings Sync: Account status changed from uninitialized to unavailable
2025-11-10 18:09:12.839 [info] [Cloud Changes] Prompting to enable cloud changes, has application previously launched from Continue On flow: false
2025-11-10 18:09:14.658 [info] [Window] [perf] Render performance baseline is 18ms
2025-11-10 18:09:16.226 [error] [Window] RangeError: Invalid language tag: furry-owo
    at Number.toLocaleString (<anonymous>)
    at Ttt.getInstallLabel (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:14030)
    at Ttt.render (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:13570)
    at Ttt.update (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:12086)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:12063)
    at vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:557:9262
    at Array.forEach (<anonymous>)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:557:9240)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2413:5379)
    at UW.vb (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2413:6868)
2025-11-10 18:09:18.012 [error] [Window] RangeError: Invalid language tag: furry-owo
    at Number.toLocaleString (<anonymous>)
    at Ttt.getInstallLabel (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:14030)
    at Ttt.render (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:13570)
    at Ttt.update (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:12086)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:12063)
    at vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:557:9262
    at Array.forEach (<anonymous>)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:557:9240)
    at set extension (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2413:5379)
    at UW.vb (vscode-file://vscode-app/c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2413:6868)

```

```log
2025-11-10 18:12:11.844 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:13.344 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:14.870 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:16.423 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:17.926 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:19.452 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:20.962 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:22.484 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:24.014 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:25.542 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:27.080 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:28.582 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:30.108 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:31.621 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:33.129 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
2025-11-10 18:12:34.645 [error] [Window] An unknown ewwow occuwwed. Pwease consuwt da wog fow mowe detaiws.
```

also appears in the log sometimes


the error occurs at
```js
ERR RangeError: Invalid language tag: furry-owo
    at Number.toLocaleString (<anonymous>)
    at Ttt.getInstallLabel (workbench.desktop.main.js:1618:14030)
    at Ttt.render (workbench.desktop.main.js:1618:13570)
    at Ttt.update (workbench.desktop.main.js:1618:12086)
    at set extension (workbench.desktop.main.js:1618:12063)
    at workbench.desktop.main.js:557:9262
    at Array.forEach (<anonymous>)
    at set extension (workbench.desktop.main.js:557:9240)
    at set extension (workbench.desktop.main.js:2413:5379)
    at UW.vb (workbench.desktop.main.js:2413:6868)
```

and i believe that it is because s.toLocaleString(Rr) has s as a number which your extension is not handling correctly as when replacing s with 's' there is no error.


edit i believe that this must be an issue as i just looked and this repo has no js/ts files.

running
```js
var temp=Number.prototype.toLocaleString.bind(Number.prototype);Number.prototype.toLocaleString = (...a)=>temp.call(...a.map(e=>String(e)))
```

with windhawks "VSCode Tweaker" does fix this issue and the vscode "Doki Theme" extension can be used to fix the checksum error caused by "VSCode Tweaker".
